### PR TITLE
setup.py patched

### PR DESCRIPTION
**Pull request by peppelinux**
now oidcservice.oidc.add_on being installed

### CODE REVIEW

**Comment by rohe** [comment]
No changes. add_on is already in setup.py .

**Comment by peppelinux** [comment]
Strange, It didnt install for me with
python setup.py install

**Comment by rohe** [comment]
Ah, my fault! Had made the change in my code but not pushed it.
Done now.

**Comment by peppelinux** [comment]
You're welcome ;-)

**Pull request closed without merging**
